# Week 10-Lecture 1-Libraires

In [ ]:
x=25
y=sqrt(x)
y

NameError: name 'sqrt' is not defined

In [ ]:
def sqrt(x):
  return x**0.5

In [ ]:
y=sqrt(x)
y

5.0

In [ ]:
import math #importing the entire library

y=math.sqrt(25)# Using a function from the "math" library: (library name.function name)

y

5.0

In [ ]:
math.floor(35/4)

8

In [ ]:
35//4

8

In [ ]:
math.ceil(35/4)

9

In [ ]:
math.log2(25)

4.643856189774724

In [ ]:
math.log10(25)

1.3979400086720377

In [ ]:
import statistics # Importing the "statistics" Library

numbers=[5,10,15,20,25]
sum_of_numbers= sum(numbers)
mean=statistics.mean(numbers)
print(sum_of_numbers)
print(mean)

75
15


## Numpy
Numerical Python

In [ ]:
!pip install numpy # install the library: !pip install + Library name

In [ ]:
import numpy as np


In [ ]:
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [ ]:
b=np.array([6,7,8,9,10])
c=a+b
print(c)

d=a*b
print(d)

[ 7  9 11 13 15]
[ 6 14 24 36 50]


In [ ]:
dot_product=np.dot(a,b)
print(dot_product)

130


In [ ]:
e=np.array([11,12,13,14,15,16,17])
print(e[1:5])

[12 13 14 15]


In [ ]:
a=np.array([1,2,3,4,5])
sum_a=np.sum(a)
print(sum_a)

15


In [ ]:
array_mean=np.mean(a)
print(array_mean)
array_max=np.max(a)
print(array_max)

3.0
5


In [ ]:
i=np.array([1,2,3])
j=np.array([4,5,6])

#Broadcasting:adding a scalar to an array
k=i+2
print(k)

l=i*j
print(l)

[3 4 5]
[ 4 10 18]


In [ ]:
a=np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [ ]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
n


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(n[1,2])

6


In [ ]:
print(n[:,1])

[2 5 8]


In [ ]:
print(n[1,:])

[4 5 6]


In [ ]:
print(n.shape)

(3, 3)


In [ ]:
row_sum=np.sum(n,axis=1)
print(row_sum)

[ 6 15 24]


In [ ]:
col_sum=np.sum(n,axis=0)
print(col_sum)

[12 15 18]


In [ ]:
import numpy as np

a= np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
c=np.ones(5)
print(c)

[1. 1. 1. 1. 1.]


In [123]:
d=np.ones(4,3) # Only one input argument.
print(d)

TypeError: Cannot interpret '3' as a data type

In [122]:
d=np.ones((4,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#set seed
np.random.seed(1)
random_num=np.random.random()
print(random_num)

0.417022004702574


In [ ]:
np.random.seed(2)
random_array=np.random.randint(25, size=20) # The upper bound of each number is with 9 and total 20 numbers.
print(random_array)

[ 8 15 13  8 22 11 18 11  8  7  2 17 11 21 15 20 20  5  7  3]


In [ ]:
np.random.seed(5)
random_matrix=np.random.uniform(-1,1, (4,4))
print(random_matrix)

[[-0.55601366  0.74146461 -0.58656169  0.83722182]
 [-0.02317762  0.22348773  0.53181571  0.03683598]
 [-0.406399   -0.62455754 -0.83851746  0.47688059]
 [-0.11738155 -0.68338026  0.75987406 -0.45182708]]
